version: "3.8"
services:
    api-postgresql:
      networks:
        - default
      container_name: api-postgresql
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8080
        - POSTGRES_USER=admin
        - POSTGRES_PASS=root
        - POSTGRES_DB=api_postgresql_database
        - POSTGRES_URL=jdbc:postgresql://db:5432/api_postgresql_database
        - JWT_SECRET=ekfjnrsanfrfwamnkr
        - JWT_LIFETIME=60000
      ports:
        - 8080:8080
    db:
      image: postgres:16.1-alpine3.19
      networks:
        - default
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
        POSTGRES_DB: api_postgresql_database
      ports:
        - 5432:5432