version: "3.8"
services:
    api-postgressql:
      networks:
        - default
      container_name: api-postgressql
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8080
        - POSTGRES_USER=admin
        - POSTGRES_PASS=root
        - POSTGRES_DB=database
        - POSTGRES_URL=jdbc:postgresql://db:5432/database
        - JWT_SECRET=ekfjnrsanfrfwamnkr
        - JWT_LIFETIME=60000
#        - ARGS="--spring.application.name=social-network-REST-API --spring.datasource.url=jdbc:postgresql://db:5432/database --spring.datasource.username=admin --spring.datasource.password=root --spring.datasource.driver-class-name=org.postgresql.Driver --socialnetworkrestapi.app.secret=ekfjnrsanfrfwamnkr --socialnetworkrestapi.app.lifetime=60000"
      ports:
        - 8080:8080
    db:
      image: postgres:16.1-alpine3.19
      networks:
        - default
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
        POSTGRES_DB: database
      ports:
        - 5432:5432