version: "3.8"
services:
    api-postgressql:
      networks:
        - default
      container_name: api-postgressql
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8080
        - POSTGRES_USER=admin
        - POSTGRES_PASS=root
        - POSTGRES_DB=database
        - POSTGRES_URL=jdbc:postgresql://db:5432/database
        - JWT_SECRET=ekfjnrsanfrfwamnkr
        - JWT_LIFETIME=60000
      ports:
        - 8080:8080
    db:
      image: postgres:16.1-alpine3.19
      networks:
        - default
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
        POSTGRES_DB: database
      ports:
        - 5432:5432
    message_broker:
      image: rabbitmq
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
        - rabbitmq
      restart: unless-stopped

networks:
  rabbitmq:
    driver: bridge