version: "3.8"
services:
    postgresql-api-rabbitmq:
      networks:
        - default
      container_name: postgresql-api-rabbitmq
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8080

        - POSTGRES_URL=jdbc:postgresql://db:5432/database
        - POSTGRES_DB=database
        - POSTGRES_USER=admin
        - POSTGRES_PASS=root

        - RABBITMQ_HOST=message_broker
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASS=guest
      ports:
        - 8080:8080
    db:
      image: postgres:16.1-alpine3.19
      networks:
        - default
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
        POSTGRES_DB: database
      ports:
        - 5432:5432
    message_broker:
      image: rabbitmq:3.13.3-management
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge